'use strict';function t(e,a,b,c){e.v.oc(e.Za,a,b,c,void 0)}function D(e,a,b,c){e.v.sa?t(e,a,b,c):e.v.kf()._OnMessageFromDOM({type:"event",component:e.Za,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function G(e,a,b){e.v.C(e.Za,a,b)}function H(e,a){for(const [b,c]of a)G(e,b,c)}function I(e){e.Qb||(e.v.Ve(e.ee),e.Qb=!0)}window.Da=class{constructor(e,a){this.v=e;this.Za=a;this.Qb=!1;this.ee=()=>this.Ga()}fd(){}Ga(){}};function K(e){-1!==e.Ra&&(self.clearTimeout(e.Ra),e.Ra=-1)}
window.Me=class{constructor(e,a){this.Nc=e;this.wg=a;this.Ra=-1;this.Sb=-Infinity;this.fe=()=>{this.Ra=-1;this.Sb=Date.now();this.eb=!0;this.Nc();this.eb=!1};this.Od=this.eb=!1}c(){K(this);this.fe=this.Nc=null}};"use strict";function L(e,a){const b=a.elementId,c=e.ec(b,a);e.Y.set(b,c);a.isVisible||(c.style.display="none");c.addEventListener("focus",()=>{M(e,"elem-focused",b)});c.addEventListener("blur",()=>{M(e,"elem-blurred",b)});e.Lb&&document.body.appendChild(c)}
function N(e,a,b){G(e,a,c=>{const g=e.Y.get(c.elementId);return b(g,c)})}function M(e,a,b,c){c||(c={});c.elementId=b;t(e,a,c)}
window.kd=class extends self.Da{constructor(e,a){super(e,a);this.Y=new Map;this.Lb=!0;H(this,[["create",b=>L(this,b)],["destroy",b=>{{b=b.elementId;const c=this.Y.get(b);this.md(c);this.Lb&&c.parentElement.removeChild(c);this.Y.delete(b)}}],["set-visible",b=>{this.Lb&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Lb){var c=this.Y.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";
b=b.fontSize;null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{{const c=this.Y.get(b.elementId);this.Cb(c,b)}}],["focus",b=>this.Ic(b)],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);N(this,"get-element",b=>b)}ec(){throw Error("required override");}md(){}Cb(){throw Error("required override");}Ic(e){var a=this.Y.get(e.elementId);
e.focus?a.focus():a.blur()}};"use strict";
{const e=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(k,d){const h=document.createElement("script");h.async=!1;"module"===d&&(h.type="module");return k.Gg?new Promise(l=>{const n="c3_resolve_"+a;++a;self[n]=l;h.textContent=k.Jg+`\n\nself["${n}"]();`;document.head.appendChild(h)}):new Promise((l,n)=>{h.onload=l;h.onerror=n;h.src=k;document.head.appendChild(h)})}let c=!1,g=!1;function m(){if(!c){try{new Worker("blob://",{get type(){g=!0}})}catch(k){}c=
!0}return g}let p=new Audio;const w={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function A(k){k=await B(k);return(new TextDecoder("utf-8")).decode(k)}function B(k){return new Promise((d,
h)=>{const l=new FileReader;l.onload=n=>d(n.target.result);l.onerror=n=>h(n);l.readAsArrayBuffer(k)})}const v=[];let x=0;window.RealFile=window.File;const C=[],y=new Map,E=new Map;let F=0;const J=[];self.runOnStartup=function(k){if("function"!==typeof k)throw Error("runOnStartup called without a function");J.push(k)};const f=new Set(["cordova","playable-ad","instant-games"]);window.na=class k{constructor(d){this.sa=d.Lg;this.qa=null;this.F="";this.$b=d.Ig;this.da=d.ie;this.sb={};this.Ka=this.rb=null;
this.Ob=[];this.gb=this.K=this.Pa=null;this.Oa=-1;this.Bg=()=>this.If();this.Na=[];this.B=d.ge;!this.sa||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&("module"!==this.da||m())||(this.sa=!1);f.has(this.B)&&this.sa&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this.sa=!1);this.Ub=this.ia=null;"html5"!==this.B&&"playable-ad"!==this.B||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
this.C("runtime","cordova-fetch-local-file",h=>this.sf(h));this.C("runtime","create-job-worker",()=>this.tf());"cordova"===this.B?document.addEventListener("deviceready",()=>this.Ad(d)):this.Ad(d)}c(){this.uc();this.qa&&(this.qa=this.qa.onmessage=null);this.rb&&(this.rb.terminate(),this.rb=null);this.Ka&&(this.Ka.c(),this.Ka=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}qd(){return e&&"cordova"===this.B}nc(){return e&&f.has(this.B)||navigator.standalone}async Ad(d){if("playable-ad"===
this.B){this.ia=self.c3_base64files;this.Ub={};await this.$e();for(let l=0,n=d.Sa.length;l<n;++l){var h=d.Sa[l].toLowerCase();this.Ub.hasOwnProperty(h)?d.Sa[l]={Gg:!0,Jg:this.Ub[h]}:this.ia.hasOwnProperty(h)&&(d.Sa[l]=URL.createObjectURL(this.ia[h]))}}d.Cg?this.F=d.Cg:(h=location.origin,this.F=("null"===h?"file:///":h)+location.pathname,h=this.F.lastIndexOf("/"),-1!==h&&(this.F=this.F.substr(0,h+1)));d.Ng&&(this.sb=d.Ng);h=new MessageChannel;this.qa=h.port1;this.qa.onmessage=l=>this._OnMessageFromRuntime(l.data);
window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Ef(l));this.gb=new self.Ie(this);await O(this.gb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.sa?await this.mf(d,h.port2):await this.lf(d,h.port2)}xc(d){d=this.sb.hasOwnProperty(d)?this.sb[d]:d.endsWith("/workermain.js")&&this.sb.hasOwnProperty("workermain.js")?this.sb["workermain.js"]:"playable-ad"===this.B&&this.ia.hasOwnProperty(d.toLowerCase())?
this.ia[d.toLowerCase()]:d;d instanceof Blob&&(d=URL.createObjectURL(d));return d}async fc(d,h,l){if(d.startsWith("blob:"))return new Worker(d,l);if(this.qd()&&"file:"===location.protocol)return d=await this.ub(this.$b+d),new Worker(URL.createObjectURL(new Blob([d],{type:"application/javascript"})),l);d=new URL(d,h);if(location.origin!==d.origin){d=await fetch(d);if(!d.ok)throw Error("failed to fetch worker script");d=await d.blob();return new Worker(URL.createObjectURL(d),l)}return new Worker(d,
l)}ya(){return Math.max(window.innerWidth,1)}xa(){return Math.max(window.innerHeight,1)}zd(d){var h=this.gb;return{baseUrl:this.F,windowInnerWidth:this.ya(),windowInnerHeight:this.xa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:k.mc(),projectData:d.Tg,scriptsType:d.ie,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Rg||"",exportType:d.ge,isDebug:-1<self.location.search.indexOf("debug"),
ife:!!self.Sg,jobScheduler:{inputPort:h.Tc,outputPort:h.$c,maxNumWorkers:h.yg},supportedAudioFormats:w,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.$b+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.$b+"opus.wasm.wasm",isiOSCordova:this.qd(),isiOSWebView:this.nc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async mf(d,h){var l=this.xc(d.Mg);this.rb=await this.fc(l,this.F,{type:this.da,name:"Runtime"});this.K=document.createElement("canvas");this.K.style.display=
"none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;this.rb.postMessage(Object.assign(this.zd(d),{type:"init-runtime",isInWorker:!0,messagePort:h,canvas:l,workerDependencyScripts:d.ed||[],engineScripts:d.Sa,projectScripts:d.tb,mainProjectScript:d.he,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[h,l,...P(this.gb)]);this.Ob=C.map(n=>new n(this));this.yd();self.c3_callFunction=(n,q)=>this.Pa.nf(n,q);"preview"===this.B&&(self.goToLastErrorScript=
()=>this.oc("runtime","go-to-last-error-script"))}async lf(d,h){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Ob=C.map(q=>new q(this));this.yd();var l=d.Sa.map(q=>"string"===typeof q?(new URL(q,this.F)).toString():q);Array.isArray(d.ed)&&l.unshift(...d.ed);l=await Promise.all(l.map(q=>this.Bc(q,this.da)));await Promise.all(l.map(q=>b(q,this.da)));const n=self.C3_ProjectScriptsStatus;if("module"===this.da){l=d.he;const q=
d.tb;for(let [u,r]of q)if(r||(r=u),u===l)try{r=await this.Bc(r,this.da),await b(r,this.da),"preview"!==this.B||n[u]||this.Id(u,"main script did not run to completion")}catch(z){this.Id(u,z)}else if("scriptsInEvents.js"===u||u.endsWith("/scriptsInEvents.js"))r=await this.Bc(r,this.da),await b(r,this.da)}else if(d.tb&&0<d.tb.length)try{if(await Promise.all(d.tb.map(q=>b(q[1],this.da))),Object.values(n).some(q=>!q)){self.setTimeout(()=>this.Jd(n),100);return}}catch(q){console.error("[Preview] Error loading project scripts: ",
q);self.setTimeout(()=>this.Jd(n),100);return}"preview"===this.B&&"object"!==typeof self.Og.Pg?(this.Xa(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(d=Object.assign(this.zd(d),{isInWorker:!1,messagePort:h,canvas:this.K,runOnStartupFunctions:J}),this.Cd(),this.Ka=self.C3_CreateRuntime(d),await self.C3_InitRuntime(this.Ka,
d))}Jd(d){this.Xa();d=`Failed to load project script '${Object.entries(d).filter(h=>!h[1]).map(h=>h[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+d);alert(d)}Id(d,h){this.Xa();console.error(`[Preview] Failed to load project main script (${d}): `,h);alert(`Failed to load project main script (${d}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Cd(){this.Xa()}Xa(){const d=window.Dg;d&&(d.parentElement.removeChild(d),
window.Dg=null)}async tf(){const d=await Q(this.gb);return{outputPort:d,transferables:[d]}}kf(){if(this.sa)throw Error("not available in worker mode");return this.Ka}oc(d,h,l,n,q){this.qa.postMessage({type:"event",component:d,handler:h,dispatchOpts:n||null,data:l,responseId:null},q)}rd(d,h,l,n,q){const u=F++,r=new Promise((z,V)=>{E.set(u,{resolve:z,reject:V})});this.qa.postMessage({type:"event",component:d,handler:h,dispatchOpts:n||null,data:l,responseId:u},q);return r}["_OnMessageFromRuntime"](d){const h=
d.type;if("event"===h)return this.yf(d);if("result"===h)this.Lf(d);else if("runtime-ready"===h)this.Mf();else if("alert-error"===h)this.Xa(),alert(d.message);else if("creating-runtime"===h)this.Cd();else throw Error(`unknown message '${h}'`);}yf(d){const h=d.component,l=d.handler,n=d.data,q=d.responseId;if(d=y.get(h))if(d=d.get(l)){var u=null;try{u=d(n)}catch(r){console.error(`Exception in '${h}' handler '${l}':`,r);null!==q&&this.Gb(q,!1,""+r);return}if(null===q)return u;u&&u.then?u.then(r=>this.Gb(q,
!0,r)).catch(r=>{console.error(`Rejection from '${h}' handler '${l}':`,r);this.Gb(q,!1,""+r)}):this.Gb(q,!0,u)}else console.warn(`[DOM] No handler '${l}' for component '${h}'`);else console.warn(`[DOM] No event handlers for component '${h}'`)}Gb(d,h,l){let n;l&&l.transferables&&(n=l.transferables);this.qa.postMessage({type:"result",responseId:d,isOk:h,result:l},n)}Lf(d){const h=d.responseId,l=d.isOk;d=d.result;const n=E.get(h);l?n.resolve(d):n.reject(d);E.delete(h)}C(d,h,l){let n=y.get(d);n||(n=new Map,
y.set(d,n));if(n.has(h))throw Error(`[DOM] Component '${d}' already has handler '${h}'`);n.set(h,l)}static ta(d){if(C.includes(d))throw Error("DOM handler already added");C.push(d)}yd(){for(const d of this.Ob)if("runtime"===d.Za){this.Pa=d;return}throw Error("cannot find runtime DOM handler");}Ef(d){this.oc("debugger","message",d)}Mf(){for(const d of this.Ob)d.fd()}static mc(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Ve(d){this.Na.push(d);
this.Lc()}Xf(d){d=this.Na.indexOf(d);if(-1===d)throw Error("invalid callback");this.Na.splice(d,1);this.Na.length||this.uc()}Lc(){-1===this.Oa&&this.Na.length&&(this.Oa=requestAnimationFrame(this.Bg))}uc(){-1!==this.Oa&&(cancelAnimationFrame(this.Oa),this.Oa=-1)}If(){this.Oa=-1;for(const d of this.Na)d();this.Lc()}wa(d){this.Pa.wa(d)}Fa(d){this.Pa.Fa(d)}Kc(){this.Pa.Kc()}Ab(d){this.Pa.Ab(d)}He(){return!!w["audio/webm; codecs=opus"]}async ug(d){d=await this.rd("runtime","opus-decode",{arrayBuffer:d},
null,[d]);return new Float32Array(d)}Ge(d){return/^(?:[a-z\-]+:)?\/\//.test(d)||"data:"===d.substr(0,5)||"blob:"===d.substr(0,5)}pd(d){return!this.Ge(d)}async Bc(d,h){return"cordova"===this.B&&"module"===h&&(d.startsWith("file:")||"file:"===location.protocol&&this.pd(d))?(d.startsWith(this.F)&&(d=d.substr(this.F.length)),d=await this.ub(d),URL.createObjectURL(new Blob([d],{type:"application/javascript"}))):d}async sf(d){const h=d.filename;switch(d.as){case "text":return await this.ze(h);case "buffer":return await this.ub(h);
default:throw Error("unsupported type");}}jd(d){const h=window.cordova.file.applicationDirectory+"www/"+d.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(h,q=>{q.file(l,n)},n)})}async ze(d){d=await this.jd(d);return await A(d)}vc(){if(v.length&&!(8<=x)){x++;var d=v.shift();this.af(d.filename,d.Kg,d.Fg)}}ub(d){return new Promise((h,l)=>{v.push({filename:d,Kg:n=>{x--;this.vc();h(n)},Fg:n=>{x--;this.vc();l(n)}});this.vc()})}async af(d,h,l){try{const n=await this.jd(d),q=await B(n);
h(q)}catch(n){l(n)}}async $e(){const d=[];for(const [h,l]of Object.entries(this.ia))d.push(this.Ze(h,l));await Promise.all(d)}async Ze(d,h){if("object"===typeof h)this.ia[d]=new Blob([h.str],{type:h.type}),this.Ub[d]=h.str;else{let l=await this.hf(h);l||(l=this.cf(h));this.ia[d]=l}}async hf(d){try{return await (await fetch(d)).blob()}catch(h){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
h),null}}cf(d){d=this.Rf(d);return this.Ye(d.data,d.Hg)}Rf(d){var h=d.indexOf(",");if(0>h)throw new URIError("expected comma in data: uri");var l=d.substring(h+1);h=d.substring(5,h).split(";");d=h[0]||"";const n=h[2];l="base64"===h[1]||"base64"===n?atob(l):decodeURIComponent(l);return{Hg:d,data:l}}Ye(d,h){var l=d.length;let n=l>>2,q=new Uint8Array(l),u=new Uint32Array(q.buffer,0,n),r,z;for(z=r=0;r<n;++r)u[r]=d.charCodeAt(z++)|d.charCodeAt(z++)<<8|d.charCodeAt(z++)<<16|d.charCodeAt(z++)<<24;for(l&=
3;l--;)q[z]=d.charCodeAt(z),++z;return new Blob([q],{type:h})}}}"use strict";
{const e=self.na;function a(f){return f.sourceCapabilities&&f.sourceCapabilities.firesTouchEvents||f.originalEvent&&f.originalEvent.sourceCapabilities&&f.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),c={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(f){return new Promise((k,d)=>{const h=document.createElement("link");h.onload=()=>k(h);h.onerror=l=>d(l);h.rel=
"stylesheet";h.href=f;document.head.appendChild(h)})}function w(f){return new Promise((k,d)=>{const h=new Image;h.onload=()=>k(h);h.onerror=l=>d(l);h.src=f})}async function A(f){f=URL.createObjectURL(f);try{return await w(f)}finally{URL.revokeObjectURL(f)}}function B(f){return new Promise((k,d)=>{let h=new FileReader;h.onload=l=>k(l.target.result);h.onerror=l=>d(l);h.readAsText(f)})}async function v(f,k,d){if(!/firefox/i.test(navigator.userAgent))return await A(f);var h=await B(f);h=(new DOMParser).parseFromString(h,
"image/svg+xml");const l=h.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),q=l.getAttribute("height");if(!n.includes("%")&&!q.includes("%"))return await A(f)}l.setAttribute("width",k+"px");l.setAttribute("height",d+"px");h=(new XMLSerializer).serializeToString(h);f=new Blob([h],{type:"image/svg+xml"});return await A(f)}function x(f){do{if(f.parentNode&&f.hasAttribute("contenteditable"))return!0;f=f.parentNode}while(f);return!1}const C=new Set(["canvas",
"body","html"]);function y(f){C.has(f.target.tagName.toLowerCase())&&f.preventDefault()}function E(f){(f.metaKey||f.ctrlKey)&&f.preventDefault()}self.C3_GetSvgImageSize=async function(f){f=await A(f);if(0<f.width&&0<f.height)return[f.width,f.height];{f.style.position="absolute";f.style.left="0px";f.style.top="0px";f.style.visibility="hidden";document.body.appendChild(f);const k=f.getBoundingClientRect();document.body.removeChild(f);return[k.width,k.height]}};self.C3_RasterSvgImageBlob=async function(f,
k,d,h,l){f=await v(f,k,d);const n=document.createElement("canvas");n.width=h;n.height=l;n.getContext("2d").drawImage(f,0,0,k,d);return n};let F=!1;document.addEventListener("pause",()=>F=!0);document.addEventListener("resume",()=>F=!1);function J(){try{return window.parent&&window.parent.document.hasFocus()}catch(f){return!1}}e.ta(class extends self.Da{constructor(f){super(f,"runtime");this.Td=!0;this.Qa=-1;this.bd="any";this.Kd=this.Ld=!1;this.Wc=this.ob=this.Aa=null;f.C("canvas","update-size",h=>
this.Pf(h));f.C("runtime","invoke-download",h=>this.Cf(h));f.C("runtime","raster-svg-image",h=>this.Jf(h));f.C("runtime","get-svg-image-size",h=>this.Af(h));f.C("runtime","set-target-orientation",h=>this.Nf(h));f.C("runtime","register-sw",()=>this.Kf());f.C("runtime","post-to-debugger",h=>this.Ed(h));f.C("runtime","go-to-script",h=>this.Ed(h));f.C("runtime","before-start-ticking",()=>this.rf());f.C("runtime","debug-highlight",h=>this.uf(h));f.C("runtime","enable-device-orientation",()=>this.Xe());
f.C("runtime","enable-device-motion",()=>this.We());f.C("runtime","add-stylesheet",h=>this.qf(h));f.C("runtime","alert",h=>this.Cc(h));f.C("runtime","hide-cordova-splash",()=>this.Bf());const k=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",h=>{const l=h.target;k.has(l.tagName.toLowerCase())||x(l)||h.preventDefault()});const d=f.K;window.addEventListener("selectstart",y);window.addEventListener("gesturehold",y);d.addEventListener("selectstart",y);d.addEventListener("gesturehold",
y);window.addEventListener("touchstart",y,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",y,{passive:!1}),d.addEventListener("pointerdown",y)):d.addEventListener("touchstart",y);this.lb=0;window.addEventListener("mousedown",h=>{1===h.button&&h.preventDefault()});window.addEventListener("mousewheel",E,{passive:!1});window.addEventListener("wheel",E,{passive:!1});window.addEventListener("resize",()=>this.Qf());window.addEventListener("fullscreenchange",()=>this.Ec());
window.addEventListener("webkitfullscreenchange",()=>this.Ec());window.addEventListener("mozfullscreenchange",()=>this.Ec());window.addEventListener("fullscreenerror",h=>this.Fc(h));window.addEventListener("webkitfullscreenerror",h=>this.Fc(h));window.addEventListener("mozfullscreenerror",h=>this.Fc(h));f.nc()&&window.addEventListener("focusout",()=>{{const n=document.activeElement;if(n){var h=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));h="textarea"===
h?!0:"input"===h?l.has(n.type.toLowerCase()||"text"):x(n)}else h=!1}h||(document.scrollingElement.scrollTop=0)});this.La=new Set;this.Vb=new WeakSet;this.pa=!1}rf(){"cordova"===this.v.B?(document.addEventListener("pause",()=>this.Jc(!0)),document.addEventListener("resume",()=>this.Jc(!1))):document.addEventListener("visibilitychange",()=>this.Jc(document.hidden));return{isSuspended:!(!document.hidden&&!F)}}fd(){window.addEventListener("focus",()=>this.Hb("window-focus"));window.addEventListener("blur",
()=>{this.Hb("window-blur",{parentHasFocus:J()});this.lb=0});window.addEventListener("keydown",k=>this.Dd("keydown",k));window.addEventListener("keyup",k=>this.Dd("keyup",k));window.addEventListener("dblclick",k=>this.Gc("dblclick",k,c));window.addEventListener("wheel",k=>this.Gf(k));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",k=>{this.yc(k);this.Wa("pointerdown",k)}),this.v.sa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.ob=new self.Me(()=>this.ff(),
5),this.ob.Od=!0,window.addEventListener("pointerrawupdate",k=>this.Hf(k))):window.addEventListener("pointermove",k=>this.Wa("pointermove",k)),window.addEventListener("pointerup",k=>this.Wa("pointerup",k)),window.addEventListener("pointercancel",k=>this.Wa("pointercancel",k))):(window.addEventListener("mousedown",k=>{this.yc(k);this.Hc("pointerdown",k)}),window.addEventListener("mousemove",k=>this.Hc("pointermove",k)),window.addEventListener("mouseup",k=>this.Hc("pointerup",k)),window.addEventListener("touchstart",
k=>{this.yc(k);this.Fb("pointerdown",k)}),window.addEventListener("touchmove",k=>this.Fb("pointermove",k)),window.addEventListener("touchend",k=>this.Fb("pointerup",k)),window.addEventListener("touchcancel",k=>this.Fb("pointercancel",k)));const f=()=>this.Kc();window.addEventListener("pointerup",f,!0);window.addEventListener("touchend",f,!0);window.addEventListener("click",f,!0);window.addEventListener("keydown",f,!0);window.addEventListener("gamepadconnected",f,!0)}Hb(f,k){t(this,f,k||null,m)}ya(){return this.v.ya()}xa(){return this.v.xa()}Qf(){const f=
this.ya(),k=this.xa();this.Hb("window-resize",{innerWidth:f,innerHeight:k,devicePixelRatio:window.devicePixelRatio});this.v.nc()&&(-1!==this.Qa&&clearTimeout(this.Qa),this.Fd(f,k,0))}Yf(f,k,d){-1!==this.Qa&&clearTimeout(this.Qa);this.Qa=setTimeout(()=>this.Fd(f,k,d),48)}Fd(f,k,d){const h=this.ya(),l=this.xa();this.Qa=-1;h!=f||l!=k?this.Hb("window-resize",{innerWidth:h,innerHeight:l,devicePixelRatio:window.devicePixelRatio}):10>d&&this.Yf(h,l,d+1)}Nf(f){this.bd=f.targetOrientation}qg(){const f=this.bd;
if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(k=>console.warn("[Construct 3] Failed to lock orientation: ",k));else try{let k=!1;screen.lockOrientation?k=screen.lockOrientation(f):screen.webkitLockOrientation?k=screen.webkitLockOrientation(f):screen.mozLockOrientation?k=screen.mozLockOrientation(f):screen.msLockOrientation&&(k=screen.msLockOrientation(f));k||console.warn("[Construct 3] Failed to lock orientation")}catch(k){console.warn("[Construct 3] Failed to lock orientation: ",
k)}}Ec(){const f=e.mc();f&&"any"!==this.bd&&this.qg();t(this,"fullscreenchange",{isFullscreen:f,innerWidth:this.ya(),innerHeight:this.xa()})}Fc(f){console.warn("[Construct 3] Fullscreen request failed: ",f);t(this,"fullscreenerror",{isFullscreen:e.mc(),innerWidth:this.ya(),innerHeight:this.xa()})}Jc(f){f?this.v.uc():this.v.Lc();t(this,"visibilitychange",{hidden:f})}Dd(f,k){"Backspace"===k.key&&y(k);const d=b.get(k.code)||k.code;D(this,f,{code:d,key:k.key,which:k.which,repeat:k.repeat,altKey:k.altKey,
ctrlKey:k.ctrlKey,metaKey:k.metaKey,shiftKey:k.shiftKey,timeStamp:k.timeStamp},c)}Gf(f){t(this,"wheel",{clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,deltaX:f.deltaX,deltaY:f.deltaY,deltaZ:f.deltaZ,deltaMode:f.deltaMode,timeStamp:f.timeStamp},c)}Gc(f,k,d){a(k)||D(this,f,{button:k.button,buttons:k.buttons,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,timeStamp:k.timeStamp},d)}Hc(f,k){if(!a(k)){var d=this.lb;"pointerdown"===f&&0!==d?f="pointermove":"pointerup"===
f&&0!==k.buttons&&(f="pointermove");D(this,f,{pointerId:1,pointerType:"mouse",button:k.button,buttons:k.buttons,lastButtons:d,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:k.timeStamp},c);this.lb=k.buttons;this.Gc(k.type,k,g)}}Wa(f,k){if(this.ob&&"pointermove"!==f){var d=this.ob;d.eb||(K(d),d.Sb=Date.now())}d=0;"mouse"===k.pointerType&&(d=this.lb);D(this,f,{pointerId:k.pointerId,pointerType:k.pointerType,
button:k.button,buttons:k.buttons,lastButtons:d,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:k.width||0,height:k.height||0,pressure:k.pressure||0,tangentialPressure:k.tangentialPressure||0,tiltX:k.tiltX||0,tiltY:k.tiltY||0,twist:k.twist||0,timeStamp:k.timeStamp},c);"mouse"===k.pointerType&&(d="mousemove","pointerdown"===f?d="mousedown":"pointerup"===f&&(d="mouseup"),this.Gc(d,k,g),this.lb=k.buttons)}Hf(f){this.Wc=f;f=this.ob;if(-1===f.Ra){var k=Date.now(),d=k-f.Sb,h=f.wg;
d>=h&&f.Od?(f.Sb=k,f.eb=!0,f.Nc(),f.eb=!1):f.Ra=self.setTimeout(f.fe,Math.max(h-d,4))}}ff(){this.Wa("pointermove",this.Wc);this.Wc=null}Fb(f,k){for(let d=0,h=k.changedTouches.length;d<h;++d){const l=k.changedTouches[d];D(this,f,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:k.timeStamp},c)}}yc(f){window!==window.top&&window.focus();this.Bd(f.target)&&document.activeElement&&!this.Bd(document.activeElement)&&document.activeElement.blur()}Bd(f){return!f||f===document||f===window||f===document.body||"canvas"===f.tagName.toLowerCase()}Xe(){this.Ld||(this.Ld=!0,window.addEventListener("deviceorientation",f=>this.wf(f)),window.addEventListener("deviceorientationabsolute",f=>this.xf(f)))}We(){this.Kd||(this.Kd=!0,window.addEventListener("devicemotion",
f=>this.vf(f)))}wf(f){t(this,"deviceorientation",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp,webkitCompassHeading:f.webkitCompassHeading,webkitCompassAccuracy:f.webkitCompassAccuracy},c)}xf(f){t(this,"deviceorientationabsolute",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp},c)}vf(f){let k=null;var d=f.acceleration;d&&(k={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var h=f.accelerationIncludingGravity;h&&(d={x:h.x||
0,y:h.y||0,z:h.z||0});h=null;const l=f.rotationRate;l&&(h={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});t(this,"devicemotion",{acceleration:k,accelerationIncludingGravity:d,rotationRate:h,interval:f.interval,timeStamp:f.timeStamp},c)}Pf(f){const k=this.v.K;k.style.width=f.styleWidth+"px";k.style.height=f.styleHeight+"px";k.style.marginLeft=f.marginLeft+"px";k.style.marginTop=f.marginTop+"px";this.Td&&(k.style.display="",this.Td=!1)}Cf(f){const k=f.url;f=f.filename;const d=document.createElement("a"),
h=document.body;d.textContent=f;d.href=k;d.download=f;h.appendChild(d);d.click();h.removeChild(d)}async Jf(f){var k=f.imageBitmapOpts;f=await self.C3_RasterSvgImageBlob(f.blob,f.imageWidth,f.imageHeight,f.surfaceWidth,f.surfaceHeight);k=k?await createImageBitmap(f,k):await createImageBitmap(f);return{imageBitmap:k,transferables:[k]}}async Af(f){return await self.C3_GetSvgImageSize(f.blob)}async qf(f){await p(f.url)}Kc(){var f=[...this.La];this.La.clear();if(!this.pa)for(const k of f)(f=k.play())&&
f.catch(()=>{this.Vb.has(k)||this.La.add(k)})}wa(f){if("function"!==typeof f.play)throw Error("missing play function");this.Vb.delete(f);let k;try{k=f.play()}catch(d){this.La.add(f);return}k&&k.catch(()=>{this.Vb.has(f)||this.La.add(f)})}Fa(f){this.La.delete(f);this.Vb.add(f)}Ab(f){this.pa=!!f}Bf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}uf(f){if(f.show){this.Aa||(this.Aa=document.createElement("div"),this.Aa.id="inspectOutline",document.body.appendChild(this.Aa));
var k=this.Aa;k.style.display="";k.style.left=f.left-1+"px";k.style.top=f.top-1+"px";k.style.width=f.width+2+"px";k.style.height=f.height+2+"px";k.textContent=f.name}else this.Aa&&(this.Aa.style.display="none")}Kf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ed(f){window.c3_postToMessagePort&&(f.from="runtime",window.c3_postToMessagePort(f))}nf(f,k){return this.v.rd(this.Za,"js-invoke-function",{name:f,params:k},void 0,void 0)}Cc(f){alert(f.message)}})}"use strict";
async function O(e){if(e.vg)throw Error("already initialised");e.vg=!0;var a=e.Zb.xc("dispatchworker.js");e.Pc=await e.Zb.fc(a,e.F,{name:"DispatchWorker"});a=new MessageChannel;e.Tc=a.port1;e.Pc.postMessage({type:"_init","in-port":a.port2},[a.port2]);e.$c=await Q(e)}function P(e){return[e.Tc,e.$c]}
async function Q(e){const a=e.Ud.length;var b=e.Zb.xc("jobworker.js");b=await e.Zb.fc(b,e.F,{name:"JobWorker"+a});const c=new MessageChannel,g=new MessageChannel;e.Pc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":g.port2},[c.port2,g.port2]);e.Ud.push(b);return g.port1}
self.Ie=class{constructor(e){this.Zb=e;this.F=e.F;this.F="preview"===e.B?this.F+"c3/workers/":this.F+e.$b;this.yg=Math.min(navigator.hardwareConcurrency||2,16);this.Pc=null;this.Ud=[];this.$c=this.Tc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.na({Lg:!1,Mg:"workermain.js",Sa:["scripts/c3runtime.js"],tb:[],he:"",ie:"module",Ig:"scripts/",ed:[],ge:"html5"}));"use strict";
async function R(e,a){a=a.type;let b=!0;0===a?b=await S():1===a&&(b=await T());t(e,"permission-result",{type:a,result:b})}async function S(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request orientation permission: ",e),!1}}
async function T(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request motion permission: ",e),!1}}self.na.ta(class extends self.Da{constructor(e){super(e,"touch");G(this,"request-permission",a=>R(this,a))}});"use strict";self.na.ta(class extends self.Da{constructor(e){super(e,"mouse");G(this,"cursor",a=>{document.documentElement.style.cursor=a})}});
"use strict";
{const e=180/Math.PI;self.ea=class extends self.Da{constructor(a){super(a,"audio");this.Nb=this.f=null;this.Pb=this.Sc=!1;this.ra=()=>this.rg();this.ba=[];this.D=[];this.ha=null;this.Vd="";this.Wd=-1;this.nb=new Map;this.Xc=1;this.pa=!1;this.cd=0;this.bc=1;this.Qc=0;this.Yd="HRTF";this.Pd="inverse";this.Zd=600;this.Xd=1E4;this.ae=1;this.Rd=this.ad=!1;this.de=this.v.He();this.ca=new Map;this.Ia=new Set;this.Uc=!1;this.Yc="";this.Ba=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.Ff(b,c);this.Mb=null;
self.C3Audio_GetOutputStream=()=>this.zf();self.C3Audio_DOMInterface=this;H(this,[["create-audio-context",b=>this.bf(b)],["play",b=>this.Sf(b)],["stop",b=>this.og(b)],["stop-all",()=>this.pg()],["set-paused",b=>this.hg(b)],["set-volume",b=>this.mg(b)],["fade-volume",b=>this.gf(b)],["set-master-volume",b=>this.fg(b)],["set-muted",b=>this.gg(b)],["set-silent",b=>this.jg(b)],["set-looping",b=>this.eg(b)],["set-playback-rate",b=>this.ig(b)],["seek",b=>this.Zf(b)],["preload",b=>this.Tf(b)],["unload",b=>
this.sg(b)],["unload-all",()=>this.tg()],["set-suspended",b=>this.kg(b)],["add-effect",b=>this.wd(b)],["set-effect-param",b=>this.bg(b)],["remove-effects",b=>this.Vf(b)],["tick",b=>this.Of(b)],["load-state",b=>this.Df(b)]])}async bf(a){a.isiOSCordova&&(this.ad=!0);this.cd=a.timeScaleMode;this.Yd=["equalpower","HRTF","soundfield"][a.panningModel];this.Pd=["linear","inverse","exponential"][a.distanceModel];this.Zd=a.refDistance;this.Xd=a.maxDistance;this.ae=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.de||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.xd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.xd()};this.Nb=this.f.createGain();this.Nb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.hc();try{await Promise.all(a.preloadList.map(c=>this.Db(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}xd(){this.Pb||(this.Sc=!1,window.addEventListener("pointerup",this.ra,!0),window.addEventListener("touchend",this.ra,!0),window.addEventListener("click",this.ra,!0),window.addEventListener("keydown",this.ra,!0),this.Pb=!0)}df(){this.Pb&&(this.Sc=!0,window.removeEventListener("pointerup",this.ra,!0),window.removeEventListener("touchend",
this.ra,!0),window.removeEventListener("click",this.ra,!0),window.removeEventListener("keydown",this.ra,!0),this.Pb=!1)}rg(){if(!this.Sc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.df()}}W(){return this.f}hc(){return this.f.currentTime}ua(){return this.Nb}nd(a){return(a=this.ca.get(a.toLowerCase()))?a[0].P():this.ua()}je(a,b){a=a.toLowerCase();let c=this.ca.get(a);
c||(c=[],this.ca.set(a,c));b.dg(c.length);b.lg(a);c.push(b);this.Hd(a)}Hd(a){let b=this.ua();const c=this.ca.get(a);if(c&&c.length){b=c[0].P();for(let g=0,m=c.length;g<m;++g){const p=c[g];g+1===m?p.S(this.ua()):p.S(c[g+1].P())}}for(const g of this.ma(a))g.Ne(b);this.Ba&&this.Yc===a&&(this.Ba.disconnect(),this.Ba.connect(b))}wb(){return this.Xc}xb(){return this.pa}cg(){this.Rd=!0}Be(a,b){return b?this.v.ug(a).then(c=>{const g=this.f.createBuffer(1,c.length,48E3);g.getChannelData(0).set(c);return g}):
new Promise((c,g)=>{this.f.decodeAudioData(a,c,g)})}wa(a){this.v.wa(a)}Fa(a){this.v.Fa(a)}sd(a){let b=0;for(let c=0,g=this.D.length;c<g;++c){const m=this.D[c];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Oe(){let a=0;for(let b=0,c=this.ba.length;b<c;++b){const g=this.ba[b];this.ba[a]=g;g.va()?g.c():++a}this.ba.length=a}*ma(a){if(a)for(const b of this.D)self.ea.Ce(b.$,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Db(a,b,c,g,m){for(const p of this.ba)if(p.Ua()===b)return await U(p),
p;if(m)return null;g&&(this.ad||this.Rd)&&this.Oe();m="audio/webm; codecs=opus"===c&&!this.de;g&&m&&this.cg();a=!g||this.ad||m?new self.xe(this,a,b,c,g,m):new self.ve(this,a,b,c,g);this.ba.push(a);await U(a);return a}async wc(a,b,c,g,m){for(const p of this.D)if(p.Ua()===b&&(p.dc()||m))return p.Qe(g),p;a=await this.Db(a,b,c,m);g="html5"===a.Mc?new self.we(a.i,a,g):new self.ye(a.i,a,g);this.D.push(g);return g}Ue(a){let b=this.nb.get(a);if(!b){let c=null;b={dd:0,promise:new Promise(g=>c=g),resolve:c};
this.nb.set(a,b)}b.dd++}Wf(a){const b=this.nb.get(a);if(!b)throw Error("expected pending tag");b.dd--;0===b.dd&&(b.resolve(),this.nb.delete(a))}tc(a){a||(a=this.Vd);return(a=this.nb.get(a))?a.promise:Promise.resolve()}Eb(){if(0<this.Ia.size)I(this);else for(const a of this.D)if(a.od()){I(this);break}}Ga(){for(var a of this.Ia)a.Ga();a=this.hc();for(var b of this.D)b.Ga(a);b=this.D.filter(c=>c.od()).map(c=>c.Ta());t(this,"state",{tickCount:this.Wd,audioInstances:b,analysers:[...this.Ia].map(c=>c.Ee())});
0===b.length&&0===this.Ia.size&&this.Qb&&(this.v.Xf(this.ee),this.Qb=!1)}pc(a,b,c){t(this,"trigger",{type:a,tag:b,aiid:c})}async Sf(a){const b=a.originalUrl,c=a.url,g=a.type,m=a.isMusic,p=a.tag,w=a.isLooping,A=a.vol,B=a.pos,v=a.panning;let x=a.off;0<x&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+this.f.currentTime);this.Vd=p;this.Ue(p);try{this.ha=await this.wc(b,c,g,p,m),v?(this.ha.zb(!0),this.ha.Pe(v.x,
v.y,v.angle,v.innerAngle,v.outerAngle,v.outerGain),v.hasOwnProperty("uid")&&this.ha.Re(v.uid)):this.ha.zb(!1),this.ha.Play(w,A,B,x)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Wf(p)}I(this)}og(a){a=a.tag;for(const b of this.ma(a))b.oa()}pg(){for(const a of this.D)a.oa()}hg(a){const b=a.tag;a=a.paused;for(const c of this.ma(b))a?c.Va():c.yb();this.Eb()}mg(a){const b=a.tag;a=a.vol;for(const c of this.ma(b))c.Bb(a)}async gf(a){const b=a.tag,c=a.vol,
g=a.duration;a=a.stopOnEnd;await this.tc(b);for(const m of this.ma(b))m.De(c,g,a);this.Eb()}fg(a){this.Xc=a.vol;for(const b of this.D)b.Jb()}gg(a){const b=a.tag;a=a.isMuted;for(const c of this.ma(b))c.td(a)}jg(a){this.pa=a.isSilent;this.v.Ab(this.pa);for(const b of this.D)b.Ib()}eg(a){const b=a.tag;a=a.isLooping;for(const c of this.ma(b))c.rc(a)}async ig(a){const b=a.tag;a=a.rate;await this.tc(b);for(const c of this.ma(b))c.vd(a)}async Zf(a){const b=a.tag;a=a.pos;await this.tc(b);for(const c of this.ma(b))c.qc(a)}async Tf(a){const b=
a.originalUrl,c=a.url,g=a.type;a=a.isMusic;try{await this.wc(b,c,g,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async sg(a){if(a=await this.Db("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ba.indexOf(a),-1!==a&&this.ba.splice(a,1)}tg(){for(const a of this.ba)a.c();this.ba.length=0}kg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.sc(a);a&&this.f.suspend&&this.f.suspend()}Of(a){this.bc=a.timeScale;this.Qc=a.gameTime;this.Wd=a.tickCount;if(0!==
this.cd)for(var b of this.D)b.Ha();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const g of this.D)g.ga===a&&g.ud(c.x,c.y,c.angle)}}async wd(a){var b=a.type;const c=a.tag;var g=a.params;if("filter"===b)g=new self.pe(this,...g);else if("delay"===b)g=new self.ne(this,...g);else if("convolution"===b){b=null;try{b=await this.Db(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",
m);return}g=new self.me(this,b.aa,...g);g.$f(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.qe(this,...g);else if("phaser"===b)g=new self.se(this,...g);else if("gain"===b)g=new self.re(this,...g);else if("tremolo"===b)g=new self.ue(this,...g);else if("ringmod"===b)g=new self.te(this,...g);else if("distortion"===b)g=new self.oe(this,...g);else if("compressor"===b)g=new self.le(this,...g);else if("analyser"===b)g=new self.ke(this,...g);else throw Error("invalid effect type");this.je(c,
g);this.Gd()}bg(a){const b=a.index,c=a.param,g=a.value,m=a.ramp,p=a.time;a=this.ca.get(a.tag);!a||0>b||b>=a.length||(a[b].X(c,g,m,p),this.Gd())}Vf(a){a=a.tag.toLowerCase();const b=this.ca.get(a);if(b&&b.length){for(const c of b)c.c();this.ca.delete(a);this.Hd(a)}}Te(a){this.Ia.add(a);this.Eb()}Uf(a){this.Ia.delete(a)}Gd(){this.Uc||(this.Uc=!0,Promise.resolve().then(()=>this.ef()))}ef(){const a={};for(const [b,c]of this.ca)a[b]=c.map(g=>g.Ta());t(this,"fxstate",{fxstate:a});this.Uc=!1}async Df(a){const b=
a.saveLoadMode;if(3!==b)for(var c of this.D)c.va()&&1===b||(c.va()||2!==b)&&c.oa();for(const g of this.ca.values())for(const m of g)m.c();this.ca.clear();this.bc=a.timeScale;this.Qc=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.pa=a.isSilent;this.v.Ab(this.pa);this.Xc=a.masterVolume;c=[];for(const g of Object.values(a.effects))c.push(Promise.all(g.map(m=>this.wd(m))));await Promise.all(c);await Promise.all(a.playing.map(g=>this.pf(g,b)));this.Eb()}async pf(a,b){if(3!==
b){var c=a.bufferOriginalUrl,g=a.bufferUrl,m=a.bufferType,p=a.isMusic,w=a.tag,A=a.isLooping,B=a.volume,v=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.wc(c,g,m,w,p)}catch(x){console.error("[Construct 3] Audio: error loading audio state: ",x);return}b.Le(a.pan);b.Play(A,B,v,0);a.isPlaying||b.Va();b.Ac(a)}}}Ff(a,b){this.Ba&&this.Ba.disconnect();this.Yc=b.toLowerCase();this.Ba=this.f.createMediaStreamSource(a);this.Ba.connect(this.nd(this.Yc))}zf(){this.Mb||(this.Mb=this.f.createMediaStreamDestination(),
this.Nb.connect(this.Mb));return this.Mb.stream}static Ce(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Se(a){return a*e}static Ae(a){return Math.pow(10,a/20)}static ld(a){return Math.max(Math.min(self.ea.Ae(a),1),0)}static Ke(a){return Math.log(a)/Math.log(10)*20}static Je(a){return self.ea.Ke(Math.max(Math.min(a,1),0))}static Eg(a,b){return 1-Math.exp(-b*a)}};self.na.ta(self.ea)}"use strict";function U(e){e.Tb||(e.Tb=e.zc());return e.Tb}
self.gd=class{constructor(e,a,b,c,g){this.i=e;this.Ag=a;this.Ca=b;this.R=c;this.xg=g;this.Mc="";this.Tb=null}c(){this.Tb=this.i=null}zc(){}W(){return this.i.W()}jc(){return this.Ag}Ua(){return this.Ca}ic(){return this.R}va(){return this.xg}fa(){}};"use strict";
self.ve=class extends self.gd{constructor(e,a,b,c,g){super(e,a,b,c,g);this.Mc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.hb=this.ib=null;this.J.addEventListener("canplaythrough",()=>!0);this.mb=this.W().createGain();this.kb=null;this.J.addEventListener("canplay",()=>{this.ib&&(this.ib(),this.hb=this.ib=null);!this.kb&&this.J&&(this.kb=this.W().createMediaElementSource(this.J),this.kb.connect(this.mb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Ca}' error: `,m);this.hb&&(this.hb(m),this.hb=this.ib=null)})}c(){this.i.sd(this);this.mb.disconnect();this.mb=null;this.kb.disconnect();this.kb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}zc(){return new Promise((e,a)=>{this.ib=e;this.hb=a;this.J.src=this.Ca})}O(){return this.J}fa(){return this.J.duration}};"use strict";
async function W(e){if(e.za)return e.za;var a=e.i.v;if("cordova"===a.B&&a.pd(e.Ca)&&"file:"===location.protocol)e.za=await a.ub(e.Ca);else{a=await fetch(e.Ca);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);e.za=await a.arrayBuffer()}}async function aa(e){if(e.aa)return e.aa;e.aa=await e.i.Be(e.za,e.zg);e.za=null}
self.xe=class extends self.gd{constructor(e,a,b,c,g,m){super(e,a,b,c,g);this.Mc="webaudio";this.aa=this.za=null;this.zg=!!m}c(){this.i.sd(this);this.aa=this.za=null;super.c()}async zc(){try{await W(this),await aa(this)}catch(e){console.error(`[Construct 3] Failed to load audio '${this.Ca}': `,e)}}fa(){return this.aa?this.aa.duration:0}};"use strict";
{let e=0;self.hd=class{constructor(a,b,c){this.i=a;this.L=b;this.$=c;this.Kb=e++;this.M=this.W().createGain();this.M.connect(this.ua());this.A=null;this.fb=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.H=!0;this.V=this.la=this.G=!1;this.qb=1;this.Ja=!1;this.Z=1;a=this.i.cd;this.Vc=1===a&&!this.va()||2===a;this.bb=this.ga=-1;this.ce=!1}c(){this.L=this.i=null;this.A&&(this.A.disconnect(),this.A=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ua(){return this.i.nd(this.$)}wb(){return this.i.wb()}vb(){return this.Vc?
this.i.Qc:performance.now()/1E3}jc(){return this.L.jc()}Ua(){return this.L.Ua()}ic(){return this.L.ic()}va(){return this.L.va()}Qe(a){this.$=a}T(){}dc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}od(){return!this.H&&!this.T()}Ea(){}fa(){return this.L.fa()}Play(){}oa(){}Va(){}yb(){}Bb(a){this.qb=a;this.M.gain.cancelScheduledValues(0);this.bb=-1;this.M.gain.value=this.kc()}De(a,b,c){if(!this.Ja){a*=this.wb();var g=this.M.gain;g.cancelScheduledValues(0);var m=this.i.hc();b=m+b;g.setValueAtTime(g.value,
m);g.linearRampToValueAtTime(a,b);this.qb=a;this.bb=b;this.ce=c}}Jb(){this.Bb(this.qb)}Ga(a){-1!==this.bb&&a>=this.bb&&(this.bb=-1,this.ce&&this.oa(),this.i.pc("fade-ended",this.$,this.Kb))}kc(){const a=this.qb*this.wb();return isFinite(a)?a:0}td(a){a=!!a;this.Ja!==a&&(this.Ja=a,this.Ib())}xb(){return this.i.xb()}Ib(){}rc(){}vd(a){this.Z!==a&&(this.Z=a,this.Ha())}Ha(){}qc(){}sc(){}zb(a){a=!!a;this.fb!==a&&((this.fb=a)?(this.A||(this.A=this.W().createPanner(),this.A.panningModel=this.i.Yd,this.A.distanceModel=
this.i.Pd,this.A.refDistance=this.i.Zd,this.A.maxDistance=this.i.Xd,this.A.rolloffFactor=this.i.ae),this.M.disconnect(),this.M.connect(this.A),this.A.connect(this.ua())):(this.A.disconnect(),this.M.disconnect(),this.M.connect(this.ua())))}Pe(a,b,c,g,m,p){this.fb&&(this.ud(a,b,c),a=self.ea.Se,this.A.coneInnerAngle=a(g),this.A.coneOuterAngle=a(m),this.A.coneOuterGain=p)}ud(a,b,c){this.fb&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(c),this.ja[1]=Math.sin(c),this.ja[2]=0,this.A.setPosition(...this.ka),
this.A.setOrientation(...this.ja))}Re(a){this.ga=a}lc(){}Ne(a){const b=this.A||this.M;b.disconnect();b.connect(a)}Ta(){return{aiid:this.Kb,tag:this.$,duration:this.fa(),volume:this.qb,isPlaying:this.IsPlaying(),playbackTime:this.Ea(),playbackRate:this.Z,uid:this.ga,bufferOriginalUrl:this.jc(),bufferUrl:"",bufferType:this.ic(),isMusic:this.va(),isLooping:this.V,isMuted:this.Ja,resumePosition:this.lc(),pan:this.Fe()}}Ac(a){this.vd(a.playbackRate);this.td(a.isMuted)}Fe(){if(!this.A)return null;const a=
this.A;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Le(a){if(a){this.zb(!0);a=this.A;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.zb(!1)}}}"use strict";
self.we=class extends self.hd{constructor(e,a,b){super(e,a,b);this.L.mb.connect(this.M);this.L.onended=()=>this.Dc()}c(){this.oa();this.L.mb.disconnect();super.c()}O(){return this.L.O()}Dc(){this.H=!0;this.ga=-1;this.i.pc("ended",this.$,this.Kb)}T(){return this.O().ended}dc(){return this.H?!0:this.T()}Ea(e){let a=this.O().currentTime;e&&(a*=this.Z);this.V||(a=Math.min(a,this.fa()));return a}Play(e,a,b){const c=this.O();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==e&&(c.loop=e);this.Bb(a);c.muted&&
(c.muted=!1);if(c.currentTime!==b)try{c.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Ua()}' to position '${b}': `,g)}this.i.wa(c);this.G=this.H=!1;this.V=e;this.Z=1}oa(){const e=this.O();e.paused||e.pause();this.i.Fa(e);this.H=!0;this.G=!1;this.ga=-1}Va(){if(!(this.G||this.H||this.T())){var e=this.O();e.paused||e.pause();this.i.Fa(e);this.G=!0}}yb(){!this.G||this.H||this.T()||(this.i.wa(this.O()),this.G=!1)}Ib(){this.O().muted=this.Ja||this.xb()}rc(e){e=!!e;
this.V!==e&&(this.V=e,this.O().loop=e)}Ha(){let e=this.Z;this.Vc&&(e*=this.i.bc);try{this.O().playbackRate=e}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${e}':`,a)}}qc(e){if(!this.H&&!this.T())try{this.O().currentTime=e}catch(a){console.warn(`[Construct 3] Error seeking audio to '${e}': `,a)}}lc(){return this.Ea()}sc(e){e?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.wa(this.O()),this.la=!1)}};"use strict";
function X(e){e.j&&e.j.disconnect();e.j=null;e.Ya=null}
self.ye=class extends self.hd{constructor(e,a,b){super(e,a,b);this.j=null;this.Wb=c=>this.Dc(c);this.Rc=!0;this.Ya=null;this.N=this.ac=0;this.Zc=1}c(){this.oa();X(this);this.Wb=null;super.c()}Dc(e){this.G||this.la||e.target!==this.Ya||(this.H=this.Rc=!0,this.ga=-1,X(this),this.i.pc("ended",this.$,this.Kb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Rc}dc(){return!this.j||this.H?!0:this.T()}Ea(e){let a;a=this.G?this.N:this.vb()-this.ac;e&&(a*=this.Z);this.V||(a=Math.min(a,this.fa()));return a}Play(e,
a,b,c){this.Zc=1;this.Bb(a);X(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.aa;this.j.connect(this.M);this.Ya=this.j;this.j.onended=this.Wb;this.j.loop=e;this.j.start(c,b);this.G=this.H=this.Rc=!1;this.V=e;this.Z=1;this.ac=this.vb()-b}oa(){if(this.j)try{this.j.stop(0)}catch(e){}this.H=!0;this.G=!1;this.ga=-1}Va(){this.G||this.H||this.T()||(this.N=this.Ea(!0),this.V&&(this.N%=this.fa()),this.G=!0,this.j.stop(0))}yb(){!this.G||this.H||this.T()||(X(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.L.aa,this.j.connect(this.M),this.Ya=this.j,this.j.onended=this.Wb,this.j.loop=this.V,this.Jb(),this.Ha(),this.ac=this.vb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.G=!1)}kc(){return super.kc()*this.Zc}Ib(){this.Zc=this.Ja||this.xb()?0:1;this.Jb()}rc(e){e=!!e;this.V!==e&&(this.V=e,this.j&&(this.j.loop=e))}Ha(){let e=this.Z;this.Vc&&(e*=this.i.bc);this.j&&(this.j.playbackRate.value=e)}qc(e){this.H||this.T()||(this.G?this.N=e:(this.Va(),this.N=e,this.yb()))}lc(){return this.N}sc(e){e?
this.IsPlaying()?(this.la=!0,this.N=this.Ea(!0),this.V&&(this.N%=this.fa()),this.j.stop(0)):this.la=!1:this.la&&(X(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.aa,this.j.connect(this.M),this.Ya=this.j,this.j.onended=this.Wb,this.j.loop=this.V,this.Jb(),this.Ha(),this.ac=this.vb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.la=!1)}Ac(e){super.Ac(e);this.N=e.resumePosition}};"use strict";
{class e{constructor(a){this.i=a;this.f=a.W();this.Sd=-1;this.R=this.$="";this.g=null}c(){this.f=null}dg(a){this.Sd=a}lg(a){this.$=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,c,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var m=this.f.currentTime;g+=m;switch(c){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,g)}}}Ta(){return{type:this.R,tag:this.$,params:this.g}}}
self.pe=class extends e{constructor(a,b,c,g,m,p,w){super(a);this.R="filter";this.g=[b,c,g,m,p,w];this.l=this.o();this.b=this.o();this.b.gain.value=w;this.a=this.o();this.a.gain.value=1-w;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=c;this.u.detune.value=g;this.u.Q.value=m;this.u.gain.vlaue=p;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[2]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[3]=b;this.m(this.u.Q,b,c,g);break;case 4:this.g[4]=b,this.m(this.u.gain,b,c,g)}}};self.ne=class extends e{constructor(a,b,c,g){super(a);this.R="delay";this.g=[b,c,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.jb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.ab=this.o();this.ab.gain.value=c;this.l.connect(this.jb);this.l.connect(this.a);this.jb.connect(this.b);this.jb.connect(this.U);this.U.connect(this.ab);this.ab.connect(this.jb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.jb.disconnect();this.U.disconnect();this.ab.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){const m=self.ea.ld;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 4:this.g[1]=m(b);this.m(this.ab.gain,m(b),c,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,c,g)}}};self.me=class extends e{constructor(a,b,c,g){super(a);this.R="convolution";this.g=[c,g];this.Nd=this.Md="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.$a=this.f.createConvolver();this.$a.normalize=c;this.$a.buffer=b;this.l.connect(this.$a);this.l.connect(this.a);this.$a.connect(this.b)}c(){this.l.disconnect();this.$a.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}$f(a,b){this.Md=a;this.Nd=b}Ta(){const a=
super.Ta();a.bufferOriginalUrl=this.Md;a.bufferUrl="";a.bufferType=this.Nd;return a}};self.qe=class extends e{constructor(a,b,c,g,m,p){super(a);this.R="flanger";this.g=[b,c,g,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.cb=this.o();this.cb.gain.value=m;this.U=this.f.createDelay(b+c);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.I=this.o();this.I.gain.value=c;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.cb);this.cb.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.cb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,c,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,c,g);break;case 8:this.g[3]=b/100,this.m(this.cb.gain,b/100,c,g)}}};self.se=class extends e{constructor(a,b,c,g,m,p,w){super(a);this.R="phaser";this.g=[b,c,g,m,p,w];this.l=this.o();this.a=this.o();this.a.gain.value=1-w/2;this.b=this.o();this.b.gain.value=w/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
c;this.u.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=p;this.I=this.o();this.I.gain.value=m;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.I);this.I.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[1]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[2]=b;this.m(this.u.Q,b,c,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,c,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,c,g)}}};self.re=class extends e{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,g){const m=self.ea.ld;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),c,g)}}};self.ue=class extends e{constructor(a,b,c){super(a);this.R="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=c/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,c,g);this.m(this.I.gain,b/2,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.te=class extends e{constructor(a,b,c){super(a);this.R="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.pb=this.o();this.pb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.pb.gain);this.s.start(0);this.l.connect(this.pb);this.l.connect(this.a);this.pb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.pb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,c,g);
this.m(this.a.gain,1-b,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.oe=class extends e{constructor(a,b,c,g,m,p){super(a);this.R="distortion";this.g=[b,c,g,m,p];this.l=this.o();this.Yb=this.o();this.Xb=this.o();this.ag(g,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.cc=this.f.createWaveShaper();this.Oc=new Float32Array(65536);this.jf(b,c);this.cc.curve=this.Oc;this.l.connect(this.Yb);this.l.connect(this.a);this.Yb.connect(this.cc);this.cc.connect(this.Xb);
this.Xb.connect(this.b)}c(){this.l.disconnect();this.Yb.disconnect();this.cc.disconnect();this.Xb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}ag(a,b){.01>a&&(a=.01);this.Yb.gain.value=a;this.Xb.gain.value=Math.pow(1/a,.6)*b}jf(a,b){for(let c=0;32768>c;++c){let g=c/32768;g=this.ng(g,a,b);this.Oc[32768+c]=g;this.Oc[32768-c-1]=-g}}ng(a,b,c){c=1.05*c*b-b;const g=0>a?-a:a;return(g<b?g:b+c*self.ea.Eg(g-b,1/c))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}};self.le=class extends e{constructor(a,b,c,g,m,p){super(a);this.R="compressor";this.g=[b,c,g,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=g;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.ke=class extends e{constructor(a,b,c){super(a);this.R="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Qd=new Float32Array(this.h.frequencyBinCount);this.be=new Uint8Array(b);this.$d=this.Ma=0;this.i.Te(this)}c(){this.i.Uf(this);this.h.disconnect();super.c()}Ga(){this.h.getFloatFrequencyData(this.Qd);this.h.getByteTimeDomainData(this.be);const a=this.h.fftSize;let b=this.Ma=0;for(var c=0;c<a;++c){let g=(this.be[c]-128)/128;0>g&&(g=-g);
this.Ma<g&&(this.Ma=g);b+=g*g}c=self.ea.Je;this.Ma=c(this.Ma);this.$d=c(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Ee(){return{tag:this.$,index:this.Sd,peak:this.Ma,rms:this.$d,binCount:this.h.frequencyBinCount,freqBins:this.Qd}}}}"use strict";
{function e(a){a.stopPropagation()}self.na.ta(class extends self.kd{constructor(a){super(a,"sliderbar")}ec(a,b){const c=document.createElement("input");c.type="range";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("touchstart",e);c.addEventListener("touchmove",e);c.addEventListener("touchend",e);c.addEventListener("mousedown",e);c.addEventListener("mouseup",e);c.addEventListener("keydown",e);c.addEventListener("keyup",e);c.addEventListener("click",
()=>{var g;g||(g={});g.elementId=a;D(this,"click",g)});c.addEventListener("change",()=>M(this,"change",a,{value:parseFloat(c.value)}));c.addEventListener("input",()=>M(this,"input",a,{value:parseFloat(c.value)}));b.id&&(c.id=b.id);this.Cb(c,b);return c}Cb(a,b){a.max=b.max;a.min=b.min;a.step=b.step;a.value=b.value;a.disabled=!b.isEnabled;a.title=b.title}})}"use strict";
function ba(e){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>t(e,"sw-message",a.data))}
function ca(e){e=e.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(e):screen.webkitLockOrientation?a=screen.webkitLockOrientation(e):screen.mozLockOrientation?a=screen.mozLockOrientation(e):screen.msLockOrientation&&(a=screen.msLockOrientation(e));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.na.ta(class extends self.Da{constructor(e){super(e,"browser");this.B="";H(this,[["get-initial-state",a=>{this.B=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>ba(this)],
["alert",a=>this.Cc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ic(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>ca(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===b)window.forward();else if("home"===b)window.home();else if("reload"===b)location.reload();else if("url"===b){b=a.url;var c=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.Qg||(2===c?window.top.location=b:1===c?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,c=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,c))}],
["request-fullscreen",a=>{{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?
document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{t(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{t(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{t(this,"hashchange",{location:location.toString()})});
document.addEventListener("backbutton",()=>{t(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",a=>{a.handled=!0;t(this,"backbutton")})}Cc(e){alert(e.message)}Ic(e){e=e.isFocus;if("nwjs"===this.B){const a="nwjs"===this.B?nw.Window.get():null;e?a.focus():a.blur()}else e?window.focus():window.blur()}});"use strict";
function Y(e,a,b){Z(e,a,URL.createObjectURL(new Blob([b.html],{type:"text/html"})));e.Rb=!0}function Z(e,a,b){a.src.startsWith("blob:")&&e.Rb&&URL.revokeObjectURL(a.src);a.src=b}
self.na.ta(class extends self.kd{constructor(e){super(e,"iframe");this.Rb=!1;N(this,"navigate-url",(a,b)=>{Z(this,a,b.url);this.Rb=!1});N(this,"display-html",(a,b)=>Y(this,a,b))}ec(e,a){e=document.createElement("iframe");e.style.position="absolute";e.style.border="none";var b=navigator.userAgent;/iphone|ipad|ipod/i.test(b)&&(b=/(iphone\s+os|ipad[^)]*os)\s+([0-9_]+)/i.exec(b),b=parseInt(b[b.length-1]),12>=b||isNaN(b))&&(e.setAttribute("noresize","noresize"),e.setAttribute("scrolling","no"));a.isVisible||
(e.style.display="none");a.id&&(e.id=a.id);a.allow&&(e.setAttribute("allow",a.allow),a.allow.includes("fullscreen")&&e.setAttribute("allowfullscreen",""));a.enableSandbox&&e.setAttribute("sandbox",a.sandbox);a.url?e.src=a.url:a.html&&Y(this,e,a);return e}Cb(){}md(e){Z(this,e,"");this.Rb=!1}});
